name: Build & Push Docker Image

# Trigger: Jalan setiap kali ada push ke branch main atau master
on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil kode dari repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Buat file .env dari Secrets (Inject API Key)
      # Ini trik penting karena Dotenv Webpack butuh file .env saat build
      - name: Create .env file
        run: |
          echo "SPOONACULAR_API_KEY=${{ secrets.SPOONACULAR_API_KEY }}" >> .env
          echo "GNEWS_API_KEY=${{ secrets.GNEWS_API_KEY }}" >> .env

      # 3. Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build Docker Image dan Push ke Docker Hub
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Ganti 'username-kamu' dengan username Docker Hub asli kamu
          # Format: username/nama-repository:tag
          tags: ${{ secrets.DOCKER_USERNAME }}/sugar-control-app:latest